"""
Subdomain Enumeration Module — async DNS brute-force.

Default wordlist: config/wordlists/subdomains.txt (~600 curated labels).
Deep mode: config/wordlists/subdomains_large.txt (150k+ permutation-based
labels generated by scripts/generate_wordlists.py).
"""

import asyncio
import socket
import os
from pathlib import Path
from core.orchestrator import EngagementState, Finding, Severity

WORDLIST_DIR = os.path.join(os.path.dirname(__file__), "..", "config", "wordlists")
WORDLIST_PATH = os.path.join(WORDLIST_DIR, "subdomains.txt")
LARGE_WORDLIST_PATH = os.path.join(WORDLIST_DIR, "subdomains_large.txt")

CONCURRENT = 50
DEEP_CONCURRENT = 300  # higher DNS concurrency needed for a 150k+ label wordlist
CHUNK = 5000


def _load_wordlist(path: str) -> list:
    try:
        with open(path, "r", encoding="utf-8") as f:
            return [line.strip() for line in f if line.strip() and not line.startswith("#")]
    except FileNotFoundError:
        return FALLBACK_SUBDOMAINS


FALLBACK_SUBDOMAINS = [
    "www", "mail", "ftp", "admin", "portal", "dev", "staging", "test",
    "api", "app", "vpn", "remote", "webmail", "blog", "shop", "cdn",
    "static", "media", "images", "docs", "wiki", "help", "support",
    "beta", "alpha", "demo", "sandbox", "uat", "qa", "prod", "backup",
    "db", "mysql", "redis", "mongo", "elastic", "jenkins", "gitlab",
    "smtp", "ns1", "ns2", "dns", "proxy", "gateway", "internal",
    "intranet", "auth", "login", "sso", "oauth", "accounts", "payment",
    "billing", "search", "graphql", "rest", "webhook", "monitor",
    "dashboard", "panel", "cpanel", "phpmyadmin", "old", "new", "secure",
]


async def resolve_subdomain(subdomain: str, domain: str, semaphore: asyncio.Semaphore) -> dict:
    fqdn = f"{subdomain}.{domain}"
    async with semaphore:
        try:
            loop = asyncio.get_event_loop()
            info = await loop.run_in_executor(None, socket.getaddrinfo, fqdn, None)
            ips = list(set(i[4][0] for i in info))
            return {"fqdn": fqdn, "ips": ips, "found": True}
        except Exception:
            return {"fqdn": fqdn, "ips": [], "found": False}


def extract_domain(target: str) -> str:
    """Extract base domain from target (strip subdomains, IPs treated as-is)."""
    # If it's an IP, return as-is
    try:
        socket.inet_aton(target)
        return target
    except OSError:
        pass
    parts = target.split(".")
    if len(parts) >= 2:
        return ".".join(parts[-2:])
    return target


async def run_subdomain_enum(state: EngagementState, console=None,
                              wordlist_path: str = None, deep: bool = False) -> dict:
    target = state.target
    domain = extract_domain(target)

    def log(msg):
        if console:
            console.print(f"  [dim]→[/dim] {msg}")

    if wordlist_path:
        wl_path = wordlist_path
    elif deep:
        wl_path = LARGE_WORDLIST_PATH if os.path.isfile(LARGE_WORDLIST_PATH) else WORDLIST_PATH
    else:
        wl_path = WORDLIST_PATH
    wordlist = _load_wordlist(wl_path)

    concurrency = DEEP_CONCURRENT if deep else CONCURRENT
    mode_label = "deep scan" if deep else "standard scan"
    log(f"Subdomain brute-force: {domain} ({len(wordlist):,} words, "
        f"{concurrency} concurrent, {mode_label})")

    semaphore = asyncio.Semaphore(concurrency)
    found = []
    checked = 0
    # Chunked so a 150k+ label wordlist doesn't hold every coroutine/task
    # object in memory at once.
    for i in range(0, len(wordlist), CHUNK):
        chunk = wordlist[i:i + CHUNK]
        tasks = [resolve_subdomain(sub, domain, semaphore) for sub in chunk]
        results = await asyncio.gather(*tasks, return_exceptions=True)
        checked += len(chunk)

        for result in results:
            if isinstance(result, dict) and result.get("found"):
                found.append(result)
                log(f"[green]Found:[/green] {result['fqdn']} → {', '.join(result['ips'])}")
                state.add_finding(Finding(
                    title=f"Subdomain found: {result['fqdn']}",
                    severity=Severity.INFO,
                    description=f"Subdomain {result['fqdn']} resolves to {', '.join(result['ips'])}",
                    evidence=f"DNS resolution: {result['fqdn']} → {result['ips']}",
                    mitre_tactic="Reconnaissance",
                    mitre_technique="T1596.001 - DNS/Passive DNS",
                    remediation="Audit all subdomains and ensure none expose unintended services.",
                    phase="subdomain",
                ))

        if deep and len(wordlist) > CHUNK:
            log(f"  ...{checked:,}/{len(wordlist):,} checked ({len(found)} found so far)")

    subdomain_data = {
        "domain": domain,
        "found": found,
        "total_checked": len(wordlist),
    }

    if not hasattr(state, "subdomains"):
        state.subdomains = []
    state.subdomains = found
    state.recon_data["subdomains"] = subdomain_data

    log(f"Subdomain enum complete: {len(found)}/{len(wordlist)} found")
    state.add_note(f"Subdomain enum: {len(found)} subdomains found for {domain}")
    return subdomain_data


# ── Plugin registration ───────────────────────────────────────────────────────

from core.plugin import Plugin, PluginResult  # noqa: E402
from core.orchestrator import Phase  # noqa: E402
from core.registry import register  # noqa: E402


@register
class SubdomainPlugin(Plugin):
    name = "subdomain"
    display_name = "Subdomain Enumeration"
    phase = Phase.SUBDOMAIN
    depends_on = []  # only needs the target, not recon's output — can run in parallel with recon
    icon = "◆"

    def enabled(self, ctx) -> bool:
        return ctx.flag("subdomains")

    async def run(self, ctx) -> PluginResult:
        data = await run_subdomain_enum(ctx.state, ctx.console, deep=ctx.flag("deep"))
        found = len(data.get("found", []))
        return PluginResult(data=data, summary=[f"Subdomains: {found} found"])
