#!/usr/bin/env python3
"""
Generates large, permutation-based discovery wordlists for GhostRecon.

Combines a curated seed list (high-signal, hand-picked paths/subdomains)
with combinatorial expansion over an English dictionary so that the
'large' / '--deep' wordlist tiers can cover hundreds of thousands of
candidates instead of a few hundred.

Run manually to regenerate:
    python3 scripts/generate_wordlists.py
"""

import os
import random

ROOT = os.path.join(os.path.dirname(__file__), "..")
WORDLIST_DIR = os.path.join(ROOT, "config", "wordlists")
DICT_PATH = "/usr/share/dict/words"

TARGET_ENDPOINTS = 250_000
TARGET_SUBDOMAINS = 150_000

ENDPOINT_PREFIXES = [
    "", "api/", "admin/", "backup/", "old/", "dev/", "test/", "staging/",
    "internal/", "uploads/", "assets/", "static/", "includes/", "config/",
    "v1/", "v2/", "private/", "tmp/", "data/", "files/",
]
ENDPOINT_SUFFIXES = [
    "", ".php", ".html", ".htm", ".asp", ".aspx", ".jsp", ".json", ".xml",
    ".txt", ".bak", ".old", ".zip", ".tar.gz", ".sql", ".log", ".yml",
    ".yaml", ".env", ".config", ".cfg", ".ini", ".swp", "~",
]

SUBDOMAIN_PREFIXES = ["", "dev-", "stage-", "staging-", "test-", "api-", "internal-", "old-", "new-", "v2-"]
SUBDOMAIN_SUFFIXES = ["", "-dev", "-test", "-staging", "-api", "-internal", "-old", "-01", "-02", "-1", "-2"]


def load_dictionary_words(min_len=3, max_len=12, limit=6000):
    if not os.path.isfile(DICT_PATH):
        return []
    words = []
    with open(DICT_PATH, "r", encoding="utf-8", errors="ignore") as f:
        for line in f:
            w = line.strip().lower()
            if w.isalpha() and min_len <= len(w) <= max_len and "'" not in w:
                words.append(w)
    words = sorted(set(words))
    random.Random(1337).shuffle(words)
    return words[:limit]


def load_lines(path):
    if not os.path.isfile(path):
        return []
    with open(path, "r", encoding="utf-8") as f:
        return [l.strip() for l in f if l.strip() and not l.startswith("#")]


def generate_endpoints():
    seed = load_lines(os.path.join(WORDLIST_DIR, "endpoints.txt"))
    words = load_dictionary_words(limit=4000)

    out = []
    seen = set(seed)
    out.extend(seed)

    for w in words:
        for prefix in ENDPOINT_PREFIXES:
            for suffix in ENDPOINT_SUFFIXES:
                path = "/" + prefix + w + suffix
                if path not in seen:
                    seen.add(path)
                    out.append(path)
                if len(out) >= TARGET_ENDPOINTS:
                    return out
    return out


def generate_subdomains():
    seed = load_lines(os.path.join(WORDLIST_DIR, "subdomains.txt"))
    words = load_dictionary_words(limit=3000)

    out = []
    seen = set(seed)
    out.extend(seed)

    for w in words:
        for prefix in SUBDOMAIN_PREFIXES:
            for suffix in SUBDOMAIN_SUFFIXES:
                label = (prefix + w + suffix).strip("-")
                if not label or len(label) > 63:
                    continue
                if label not in seen:
                    seen.add(label)
                    out.append(label)
                if len(out) >= TARGET_SUBDOMAINS:
                    return out
    return out


def main():
    os.makedirs(WORDLIST_DIR, exist_ok=True)

    endpoints = generate_endpoints()
    with open(os.path.join(WORDLIST_DIR, "endpoints_large.txt"), "w", encoding="utf-8") as f:
        f.write(f"# Auto-generated by scripts/generate_wordlists.py — {len(endpoints)} entries\n")
        f.write("# Seed paths (curated) + dictionary x prefix x extension permutations\n")
        for p in endpoints:
            f.write(p + "\n")
    print(f"Wrote {len(endpoints)} endpoints -> config/wordlists/endpoints_large.txt")

    subdomains = generate_subdomains()
    with open(os.path.join(WORDLIST_DIR, "subdomains_large.txt"), "w", encoding="utf-8") as f:
        f.write(f"# Auto-generated by scripts/generate_wordlists.py — {len(subdomains)} entries\n")
        f.write("# Seed subdomains (curated) + dictionary x env-prefix/suffix permutations\n")
        for s in subdomains:
            f.write(s + "\n")
    print(f"Wrote {len(subdomains)} subdomains -> config/wordlists/subdomains_large.txt")


if __name__ == "__main__":
    main()
